apps/backend/package.json, pnpm-lock.yaml
=> ✨ add prisma

flake.lock, flake.nix
=> ✨ add flakes for openapi-generator-cli

package.json, packages/kernel/jest.config.js, packages/kernel/package.json, packages/kernel/src/checker.test.ts, packages/kernel/src/checker.ts, packages/kernel/src/test-util.ts, packages/kernel/vitest.config.ts, pnpm-lock.yaml, turbo.json
=> kernelにテストを追加

apps/backend/compose.yaml, apps/backend/prisma/schema.prisma
=> schema.prisma

apps/backend/src/generated/openapi/api/me.service.ts, openapi.yaml
=> ✨ add bearer token auth for /me endpoint

apps/backend/README.md
=> 📝 install and debug command

apps/backend/README.md, apps/backend/package.json
=> ✨ prisma studio script and description

apps/backend/prisma/schema.prisma
=> ✨ add depender-dependee table

apps/backend/prisma/schema.prisma, apps/backend/src/api/files.service.ts, apps/backend/src/app.module.ts, apps/backend/src/controllers/files.controller.ts, apps/backend/src/utils/index.ts
close #65 
close #66
close #67
動作確認済み
=> Feat/#65 #66 #67 file service

apps/backend/src/utils/index.ts
=> 🐛 encoding: base64 -> hex

apps/backend/src/api/files.service.ts, apps/backend/src/api/login.service.ts, apps/backend/src/api/me.service.ts, apps/backend/src/api/permalinks.service.ts, apps/backend/src/api/registry.service.ts, apps/backend/src/api/search.service.ts, apps/backend/src/app.module.ts, apps/backend/src/controllers/files.controller.ts, apps/backend/src/controllers/login.controller.ts, apps/backend/src/controllers/me.controller.ts, apps/backend/src/controllers/permalinks.controller.ts, apps/backend/src/controllers/registry.controller.ts, apps/backend/src/controllers/search.controller.ts
=> 🐛 fixed all api service templates

openapi.yaml
=> 🐛 fixed invalid query param

apps/backend/prisma/schema.prisma, apps/backend/src/api/files.service.ts
=> fix lower camel case

apps/backend/src/api/registry.service.ts
=> 🐛 protect private deps

apps/backend/src/api/login.service.ts, apps/backend/src/api/me.service.ts, apps/backend/src/app.module.ts, apps/backend/src/auth.service.ts, apps/backend/src/controllers/login.controller.ts, apps/backend/src/controllers/me.controller.ts
=> ✨ auth.service

apps/backend/src/main.ts, apps/web/package.json
=> fix: enable CORS for localhost and update development port to 3001

apps/web/app/[id]/edit/page.tsx, apps/web/lib/monacoConfig.ts
=> feat: add syntax configuration for editor

apps/backend/Dockerfile, apps/backend/package.json
=> ✨ add dockerfile

apps/web/app/[id]/edit/page.tsx, apps/web/components/register.tsx, apps/web/components/share.tsx, apps/web/components/sidemenu.tsx, apps/web/components/ui/button.tsx
=> change: redesign editor

apps/backend/src/api/me.service.ts
=> 🐛 duplicate filename handling

apps/backend/src/app.module.ts, apps/backend/src/controllers/me.controller.ts, apps/backend/src/jsonOnly.middleware.ts
=> backend: 諸々リファクタ

apps/web/app/[id]/view/page.tsx, apps/web/app/layout.tsx
`export const runtime = "edge";` が外れていた
ついでに`app/layout.tsx`に移動した
=> cloudflareのデプロイを直した

apps/web/app/[id]/edit/page.tsx, apps/web/components/sidemenu.tsx, apps/web/lib/drawHighlight.ts, apps/web/lib/editorEventHandler.ts, apps/web/lib/editorInteracter.ts, apps/web/lib/format.ts, apps/web/lib/monacoConfig.ts, apps/web/package.json, packages/kernel/package.json, packages/kernel/src/ast.ts, packages/kernel/src/checker.test.ts, packages/kernel/src/checker.ts, packages/kernel/src/history.test.ts, packages/kernel/src/history.ts, packages/kernel/src/kernel.ts, packages/kernel/src/parser.test.ts, packages/kernel/src/parser.ts, pnpm-lock.yaml
=> カーネルとエディタの通信

apps/web/app/[id]/edit/page.tsx, apps/web/lib/editorEventHandler.ts, apps/web/lib/userKernel.ts, packages/kernel/src/parser.ts
=> fix kernel initalization 

apps/web/app/[id]/edit/page.tsx, apps/web/lib/monacoConfig.ts
=> feat(editor): add use for keyword

apps/web/lib/monacoConfig.ts, packages/kernel/src/kernel.ts, packages/kernel/src/parser.test.ts, packages/kernel/src/parser.ts
=> パースに失敗しても途中までパースした結果を返すようにした

apps/web/app/[id]/edit/page.tsx, packages/kernel/package.json, packages/kernel/src/history.ts, packages/kernel/src/kernel.ts
=> feat(webui): add environment viewer

apps/backend/src/searchlogic/index.ts
=> 検索ロジックの抽象クラス

apps/web/app/files/page.tsx
=> ✨ display files only if available in the edit page

apps/backend/src/jsonOnly.middleware.ts
=> 🐛 empty body is not 415

apps/web/app/[id]/edit/page.tsx, apps/web/lib/editorEventHandler.ts
=> allow execution of the next command even if a syntax error occurs before

apps/backend/src/kernel/mockAnalyzer.service.ts
=> ✨ mock dependency resolution

apps/web/app/[id]/edit/page.tsx, apps/web/lib/drawHighlight.ts, apps/web/lib/editorEventHandler.ts, apps/web/lib/editorInteracter.ts
=> (wip): error massage highlight

apps/web/lib/editorEventHandler.ts
=> feat(webui): display error message when execution failed

apps/backend/compose.yaml, apps/backend/prisma/schema.prisma, apps/backend/src/api/me.service.ts, apps/backend/src/app.module.ts, apps/backend/src/controllers/me.controller.ts, apps/backend/src/main.ts
=> Feat/#145 patch /me/files/n/v

apps/backend/src/api/login.service.ts, apps/backend/src/auth.service.ts
=> ✨ add error handling for GitHub OAuth and improve state validation

apps/backend/src/controllers/me.controller.ts
=> POST /me/files/{n}/{v}/register

apps/backend/src/api/me.service.ts
=> ✨ tag validation

apps/backend/src/api/me.service.ts
=> 🐛 validate filename

apps/web/app/[id]/edit/page.tsx
=> feat(webui): support shorcutkey

apps/web/app/[id]/edit/page.tsx, apps/web/lib/editorInteracter.ts
=> fix(webui): use monaco native error message insted of custom css

apps/web/lib/monacoConfig.ts, packages/kernel/src/ast.ts, packages/kernel/src/checker.ts, packages/kernel/src/parser.test.ts, packages/kernel/src/parser.ts
=> add import, constant and axiom syntax

apps/web/app/[id]/edit/page.tsx, apps/web/lib/editorEventHandler.ts
=> fix(webui): update env even if use shortcut key

apps/backend/src/api/me.service.ts
=> ✨ restrict saving with no changes

apps/web/app/[id]/edit/page.tsx
=> fix(webui): reset message editor content when syntax error fixed

apps/backend/src/api/me.service.ts
=> ✨ set initial source code

packages/kernel/src/checker.test.ts, packages/kernel/src/checker.ts, packages/kernel/src/history.ts, packages/kernel/src/typeCheck.test.ts, packages/kernel/src/typeCheck.ts
=> constantとaxiomを実装した

apps/backend/src/api/me.service.ts, apps/backend/src/utils/index.ts
=> ✨ kanji-kana tag validation

apps/backend/src/controllers/me.controller.ts
=> 🐛 fixed bug on /me/... tag and desc

apps/backend/src/api/login.service.ts
=> update userName assignment to use dynamic login from user object

apps/backend/prisma/schema.prisma, apps/backend/src/api/login.service.ts, apps/backend/src/api/me.service.ts, apps/backend/src/generated/openapi/model/userInfo.ts, openapi.yaml
=> feat: add github_id 

packages/kernel/src/kernel.test.ts, packages/kernel/src/kernel.ts
=> Verify registration

apps/backend/src/kernel/mockAnalyzer.service.ts
close #201
時間がないのでimport非対応のバリデーションを使用
=> ✨ use validator for single source in backend

apps/backend/src/kernel/mockAnalyzer.service.ts
=> 🐛 FIX ME!!!

apps/backend/src/main.ts
=> feat: allow CORS from lapisla.net

apps/backend/src/main.ts
=> fix: update CORS origin URL by removing trailing slash

apps/backend/src/controllers/login.controller.ts
=> fix cookie info

apps/backend/src/api/timeline.service.ts
=> 🐛 fix: initialize nameToIdMap as a constant

apps/web/app/timeline/page.tsx
=> feat: initialize timelines state as an empty array

apps/web/components/tagForm.tsx
=> feat: update TagForm to trigger onChange when tags change

packages/kernel/src/ast.ts, packages/kernel/src/checker.test.ts
=> fix use (and substPreds) can capture free variables in predicate body

apps/web/app/[id]/edit/page.tsx, apps/web/lib/drawHighlight.ts, apps/web/lib/editorInteracter.ts
=> fix(webui): never grows tape when typing at edges

apps/web/app/[id]/edit/page.tsx, apps/web/app/globals.css
=> fix(webui): make environment table scrollable

openapi.yaml
=> ✨ license related api modifications

apps/backend/src/api/files.service.ts, apps/backend/src/api/login.service.ts, apps/backend/src/api/me.service.ts, apps/backend/src/api/registry.service.ts, apps/backend/src/api/search.service.ts, apps/backend/src/api/tags.service.ts, apps/backend/src/api/timeline.service.ts, apps/backend/src/controllers/files.controller.ts, apps/backend/src/controllers/login.controller.ts, apps/backend/src/controllers/me.controller.ts, apps/backend/src/controllers/registry.controller.ts, apps/backend/src/controllers/search.controller.ts, apps/backend/src/controllers/tags.controller.ts, apps/backend/src/controllers/timeline.controller.ts, apps/backend/src/kernel/codeAnalyzer.service.ts, apps/backend/src/repository.service/auth.impl.ts, apps/backend/src/repository.service/dependency.impl.ts, apps/backend/src/repository.service/index.ts, apps/backend/src/repository.service/snapshot.impl.ts, apps/backend/src/repository.service/tagAndDesc.impl.ts
=> ♻️ 🎨 refactor imports

apps/backend/src/api/search.service.ts, apps/backend/src/app.module.ts, apps/backend/src/searchlogic/index.ts
=> ✨ search by tag

apps/backend/Dockerfile, apps/backend/dev.Dockerfile
Update node.js version in backend
- fix #264
=> chore(backend): Update node.js version

apps/web/app/files/page.tsx
fix visibly of my own unpublished files
fix visibly of my own unpublished files
- fix #<issue number>
=> fix front files-get api

apps/web/components/save.tsx
Fixed save button title; "Share" -> "Save".
close #270
=> fix(webui): title of save button

CONTRIBUTING.md, README.md, README_ja.md
Small docs update.
- [add language switcher to README files](https://github.com/lapisla-prover/lapisla-prover/commit/bfaf79419e3024dca351be9586d070a8978a783f)
- [docs: rewrite code of conduct](https://github.com/lapisla-prover/lapisla-prover/commit/13d8614c5f4b0ee1e795823162ca41b1f61ea7f0)
=> update README, CONTRIBUTING.md

apps/backend/src/api/me.service.ts, apps/web/components/newfile.tsx, openapi.yaml
Describe the changes made in the pull request.
- fix #<issue number>
=> hotfix: incorrect regex

apps/backend/src/kernel/codeAnalyzer.service.ts
deny empty source code registration
close #273
=> feat(backend): deny empty source code registration

apps/web/app/[id]/edit/page.tsx, apps/web/components/save.tsx, apps/web/components/sidemenu.tsx
fix to update versions on save
- fix #221
=> fix(webfront): fix to update versions on save

apps/web/app/files/page.tsx
Describe the changes made in the pull request.
- fix #<issue number>
=> fix(front): credentials: "include"

apps/docs/app/using-lapisla/page.mdx
=> fix(docs): fix description about sharing and registeration

.github/workflows/CI.yaml
skip checking changes when CI is triggered by push
- fix #<issue number>
=> fix(CI): skip checking changes when CI is triggered by push
